### ISSUE TITLE
Cannot use OTP 

### ISSUE THREAD

**Issue by lgibelli** [t0mk/kraken-python3-cli#4]
I set export KRAKENAPI_USE_OTP=true and tried to withdraw funds using kx. I got this:

Traceback (most recent call last):
  File "./kx", line 550, in <module>
    parser.dispatch()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "./kx", line 525, in Withdraw
    return query('private', _fname, set_values(locals()))
  File "./kx", line 299, in query
    raise Exception(msg)
Exception: EAPI:Invalid signature, perhaps a missing/wrong/old OTP?

The OTP was definitely right and still valid at the moment I ran the command and also still valid *after* the command bailed out.
I retried a few times, same result.

Looks like OTP is broken?

FYI: the OTPs on google authenticator cycle every ~30 secs, not ~90 secs, you might want to lower the caching time in kx.

**Comment by lgibelli** [comment]
sorry for the noise, it was my mistake: the API key I was using was not authorized to withdraw funds. I created a new key with this privilege and now OTP works.
Still you should change the default timeout for caching OTPs.

**Comment by lgibelli** [comment]
updating the title

**Comment by t0mk** [comment]
hey, thanks for using this tool.

About the timeout - did you actually have the Kraken API saying that the OTP pass from cache file is too old?

Because Kraken API (and other OTP acceptings auth systems) will not accept only the newest OTP displayed in your auth, but also couple of older (and probably newer) OTPs. I remember trying to find out the longest possible delay - for user's convenience it's better to type OTP less, and that's how 90s ended up there. It also depends on clock sync I guess. Anyway, 90s to 30s means users will need to type OTP more, and I am a bit reluctant to make using this tool less convenient.

**Comment by lgibelli** [comment]
My bad, you are perfectly right. Kraken accepts expired OTPs. 
Note to future self: test twice before opening a ticket :)

Many thanks for writing this cli, it's nearly impossible to use the web interface due to constant server timeouts.
